language: python
python: 2.7
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3 QA=true
matrix:
  include:
    - python: 2.6
      env: PLONE_VERSION=4.1
  allow_failures:
    - python: 2.6
      env: PLONE_VERSION=4.1
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - test "$PLONE_VERSION" = "4.1" && cat travis-4.1.x.cfg > travis.cfg || true
  - test "$PLONE_VERSION" = "4.2" && sed -ie "s#collective.js.jqueryui = 1.10.1.2#collective.js.jqueryui = 1.8.16.9#" travis.cfg || true
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/test
after_success: test -v QA && make coverage-validation basic-validation || true
after_failure: bin/buildout annotate
notifications:
  irc: irc.freenode.org#simplesconsultoria
